name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 Corretto
        uses: actions/setup-java@main
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build
